name: CI

on: 
  push:
    branches:    
      - release/master 

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: '10'
    
    - name: yarn install
      run: yarn install
      
    - name: yarn build
      run: yarn run build --if-present